// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.5.1")]
public sealed partial class AddJogadoToPartida : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(AddJogadoToPartida));
    
    string IMigrationMetadata.Id
    {
        get { return "202504180111196_AddJogadoToPartida"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
